### ISSUE TITLE
Failure deploying to Windows VM

### ISSUE THREAD

**Issue by pupimvictor** [dynatrace-innovationlab/bosh-oneagent-release#63]
Hi,

When we try to deploy the Addon to a Windows TKGi cluster, which is composed by Windows and Ubuntu VMs, Bosh tries to use the Shell scripts in monit config instead of the Powershell scripts.

Monit config file in Windows VM:
```sh
PS C:\var\vcap\jobs> cat .\dynatrace-oneagent\monit
check process dynatrace-oneagent
  with pidfile /var/vcap/sys/run/dynatrace-oneagent/dynatrace-watchdog.pid
  start program "/var/vcap/jobs/dynatrace-oneagent/bin/start-oneagent.sh"
    with timeout 600 seconds
  stop program "/var/vcap/jobs/dynatrace-oneagent/bin/stop-oneagent.sh"
    with timeout 120 seconds
  group vcap
```

Example of how a monit file should look like in Windows VMs:
```json
PS C:\var\vcap\jobs> cat .\kubelet-windows\monit
{
  "processes": [
    {
      "name": "kubelet",
      "executable": "powershell",
      "args": ["C:\\var\\vcap\\jobs\\kubelet-windows\\bin\\kubelet_ctl.ps1"],
      "env": {}
    }
  ]
}
```

Error:
`Configuring job dynatrace-oneagent: Adding monit configuration: invalid character 'c' looking for beginning of value`

The error is because the monit config file in the Windows VM is not a JSON.

We have runtime configurations for both Ubuntu Xenial and Windows2019 stemcells set in Opsmanager like in the [example](https://github.com/Dynatrace/bosh-oneagent-release/blob/master/runtime-config-dynatrace.yml).

Bosh runtime config for Windows Addon:
```yml
releases:
- name: dynatrace-oneagent
  version: 1.4.0

addons:
- name: dynatrace-oneagent-sandbox2-windows-addon
  jobs:
  - name: dynatrace-oneagent
    release: dynatrace-oneagent
    properties:
      dynatrace:
        environmentid: <redacted>
        apitoken: <redacted>
        apiurl: <redacted>
        hostgroup: sevice-instance_b48b90ba-5b07-4a03-9ee4-16801560eb0d
        hosttags: cluster=TANZU_SANDBOX2 landscape=Tanzu_LS team=Tanzu_T
        hostprops: Department=Infrastructure Stage=Sandbox
        infraonly: 0
  include:
    deployments:
      - service-instance_7adea55a-5905-4768-85f9-2146c802c573

    stemcell:
      - os: windows2019
  exclude:
    lifecycle: errand
```
